-- MySQL Script generated by MySQL Workbench
-- Sun May 10 15:17:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vueling` ;

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vueling` DEFAULT CHARACTER SET utf8 ;
USE `vueling` ;

-- -----------------------------------------------------
-- Table `vueling`.`Plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueling`.`Plane` (
  `id_plane` INT NOT NULL,
  `capacity` INT NULL,
  `model` VARCHAR(45) NULL,
  PRIMARY KEY (`id_plane`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_plane_UNIQUE` ON `vueling`.`Plane` (`id_plane` ASC);


-- -----------------------------------------------------
-- Table `vueling`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueling`.`Seat` (
  `id_seat` INT NOT NULL,
  `plane_id` INT NOT NULL,
  PRIMARY KEY (`id_seat`),
  CONSTRAINT `fk_Seat_Plane`
    FOREIGN KEY (`plane_id`)
    REFERENCES `vueling`.`Plane` (`id_plane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_seat_UNIQUE` ON `vueling`.`Seat` (`id_seat` ASC);

CREATE INDEX `fk_Seat_Plane_idx` ON `vueling`.`Seat` (`plane_id` ASC);

INSERT INTO `plane` (`id_plane`, `capacity`, `model`) VALUES
(1, 525, 'Airbus A380-800'),
(2, 380, 'Airbus A340-600');

INSERT INTO `seat` (`id_seat`, `plane_id`) VALUES
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(9, 1),
(5, 2),
(6, 2),
(7, 2),
(8, 2),
(10, 2);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
